import asyncio
from enum import Enum
from typing import List, Optional
from fastapi import FastAPI
from pydantic import BaseModel, Field
import string
import random
import ast
from db import init_db, save_game, take_action_db, get_game_history, get_last_turn, update_action
from contextlib import asynccontextmanager
from ai import start_game, continue_game

@asynccontextmanager
async def lifespan(app: FastAPI):
    await init_db()
    yield

app = FastAPI(lifespan=lifespan)

alphabet_list = list(string.ascii_letters)
DEFAULT_STATS = {
  "hp": 100,
  "max_hp": 100,
  "attack": 15,
  "defence": 10,
  "gold": 50,
  "inventory": ["torch", "dagger", "bread"]
}


class GameSetting(Enum):
    DARK_FANTASY = "dark fantasy"
    SPACE_OPERA = "space opera"
    POST_APOCALYPTIC = "post-apocalyptic"
    CLASSIC_DUNGEON = "classic dungeon"


class GameInput(BaseModel):
    player_name: str = Field(..., min_length=3, max_length=16, description="Player Name")
    setting: str = Field(default=GameSetting.CLASSIC_DUNGEON, description="Game setting")


class Stats(BaseModel):
    hp: Optional[int] = Field(default=100, description="Current HP of the character")
    max_hp: Optional[int] = Field(default=100, description="Max HP of the character")
    attack: Optional[int] = Field(default=15,  description="Damage of the character")
    defence:Optional[int] = Field(default=10, description="Defence of the character")
    gold: Optional[int] = Field(default=0, description="Amount of money of the character")
    inventory: Optional[List[str]] = Field(default_factory=list, description="What items does the character have")


class GameBase(BaseModel):
    scene: str = Field(..., description="Description of the scene generated by AI")
    actions: List[str] = Field(..., description="List of possible actions generated by AI")

class GameCreate(GameBase):
    pass


class Game(GameBase):
    game_id: str = Field(..., description="Unique identifier of the Game")
    stats: Stats = Field(..., description="Character stats at the start of the game")


class Turn(BaseModel):
    result: str = Field(..., description="Result of the turn")
    actions: List[str] = Field(..., description="List of possible actions generated by AI")
    turn: int = Field(..., description="Turn number")
    stats: Stats = Field(..., description="Character stats after this turn")
    game_over: bool = Field(default=False, description="True once the character's HP has reached 0")


class TurnInput(BaseModel):
    action:str = Field(..., description="Your actions (choose one from the list e.g. 1, 2 or 3)")


def apply_stat_updates(stats: dict, updates: dict) -> dict:
    for key in ("hp", "attack", "defence", "gold"):
        delta = updates.get(key)
        if isinstance(delta, (int, float)):
            stats[key] = stats.get(key, 0) + delta

    inventory_updates = updates.get("inventory")
    if isinstance(inventory_updates, dict):
        inventory = stats.setdefault("inventory", [])
        for item in inventory_updates.get("remove") or []:
            if item in inventory:
                inventory.remove(item)
        inventory.extend(inventory_updates.get("add") or [])

    stats["hp"] = max(0, min(stats["hp"], stats["max_hp"]))
    stats["gold"] = max(0, stats["gold"])
    return stats


@app.get("/")
async def main_page():
    return "Hello World"


@app.post("/games", response_model=Game)
async def create_game(game: GameInput):
    new_game_id = "".join([random.choice(alphabet_list) for _ in range(10)])

    game_inputs = GameInput(
        player_name=game.player_name,
        setting=game.setting
    )

    game_output = await start_game(game_inputs)
    await save_game(new_game_id, game_inputs)

    new_game = Game(
        game_id=new_game_id,
        scene=game_output["scene"],
        actions=game_output["actions"],
        stats=Stats(**DEFAULT_STATS)
    )

    # Create character in "turns" table in database - no action has been taken yet
    await take_action_db(new_game_id, "", result=new_game.scene, stats=f"{DEFAULT_STATS}", turn_number=1)

    return new_game


@app.post("/games/{game_id}/action", response_model=Turn)
async def take_action(game_id: str, action: TurnInput):

    game_history = await get_game_history(game_id)
    previous_turn_number = game_history[0][2]

    # Record the player's chosen action against the turn it responds to
    await update_action(game_id=game_id, action=action.action, turn_number=previous_turn_number)

    stats_row = await get_last_turn(game_id)
    stats = ast.literal_eval(stats_row[-1])

    # Re-fetch history so the LLM sees the action just recorded above
    game_history = await get_game_history(game_id)
    response = await continue_game(game_history, stats=stats)

    updates = response.get("updates")
    if isinstance(updates, dict):
        stats = apply_stat_updates(stats, updates)
    game_over = stats["hp"] <= 0
    stats_str = str(stats)

    # This turn's action is unknown until the player's next call updates it
    turn_number = previous_turn_number + 1
    await take_action_db(game_id=game_id, action="", result=response["result"], turn_number=turn_number, stats=stats_str)

    turn = Turn(
        result=response["result"],
        actions=[] if game_over else response["actions"],
        turn=turn_number,
        stats=Stats(**stats),
        game_over=game_over
    )
    return turn