import asyncio
import json
from enum import Enum
from typing import List, Optional
from fastapi import FastAPI
from pydantic import BaseModel, Field
import string
import random
import ast
from db import init_db, save_game, take_action_db, get_game_history, get_last_turn, update_action, get_combat_state, update_combat_state
from contextlib import asynccontextmanager
from ai import start_game, continue_game, narrate_combat

@asynccontextmanager
async def lifespan(app: FastAPI):
    await init_db()
    yield

app = FastAPI(lifespan=lifespan)

alphabet_list = list(string.ascii_letters)
DEFAULT_STATS = {
  "hp": 100,
  "max_hp": 100,
  "attack": 15,
  "defence": 10,
  "gold": 50,
  "inventory": ["torch", "dagger", "bread"]
}

COMBAT_TRIGGER_WORDS = ["attacks you", "enemy appears", "monster", "lunges at you", "charges at you", "ambush"]
DEFAULT_ENEMY = {"name": "Enemy", "hp": 30, "attack": 8}


class GameSetting(Enum):
    DARK_FANTASY = "dark fantasy"
    SPACE_OPERA = "space opera"
    POST_APOCALYPTIC = "post-apocalyptic"
    CLASSIC_DUNGEON = "classic dungeon"


class GameInput(BaseModel):
    player_name: str = Field(..., min_length=3, max_length=16, description="Player Name")
    setting: str = Field(default=GameSetting.CLASSIC_DUNGEON, description="Game setting")


class Stats(BaseModel):
    hp: Optional[int] = Field(default=100, description="Current HP of the character")
    max_hp: Optional[int] = Field(default=100, description="Max HP of the character")
    attack: Optional[int] = Field(default=15,  description="Damage of the character")
    defence:Optional[int] = Field(default=10, description="Defence of the character")
    gold: Optional[int] = Field(default=0, description="Amount of money of the character")
    inventory: Optional[List[str]] = Field(default_factory=list, description="What items does the character have")


class GameBase(BaseModel):
    scene: str = Field(..., description="Description of the scene generated by AI")
    actions: List[str] = Field(..., description="List of possible actions generated by AI")

class GameCreate(GameBase):
    pass


class Game(GameBase):
    game_id: str = Field(..., description="Unique identifier of the Game")
    stats: Stats = Field(..., description="Character stats at the start of the game")


class CombatInfo(BaseModel):
    in_combat: bool = Field(default=False, description="Whether the player is currently fighting an enemy")
    enemy_name: Optional[str] = Field(default=None, description="Name of the current enemy, if any")
    enemy_hp: Optional[int] = Field(default=None, description="Current HP of the enemy, if any")


class Turn(BaseModel):
    result: str = Field(..., description="Result of the turn")
    actions: List[str] = Field(..., description="List of possible actions generated by AI")
    turn: int = Field(..., description="Turn number")
    stats: Stats = Field(..., description="Character stats after this turn")
    game_over: bool = Field(default=False, description="True once the character's HP has reached 0")
    combat: CombatInfo = Field(default_factory=CombatInfo, description="Current combat encounter, if any")


class TurnInput(BaseModel):
    action:str = Field(..., description="Your actions (choose one from the list e.g. 1, 2 or 3)")


def apply_stat_updates(stats: dict, updates: dict) -> dict:
    for key in ("hp", "attack", "defence", "gold"):
        delta = updates.get(key)
        if isinstance(delta, (int, float)):
            stats[key] = stats.get(key, 0) + delta

    inventory_updates = updates.get("inventory")
    if isinstance(inventory_updates, dict):
        inventory = stats.setdefault("inventory", [])
        for item in inventory_updates.get("remove") or []:
            if item in inventory:
                inventory.remove(item)
        inventory.extend(inventory_updates.get("add") or [])

    stats["hp"] = max(0, min(stats["hp"], stats["max_hp"]))
    stats["gold"] = max(0, stats["gold"])
    return stats


def detect_combat_trigger(text: str) -> bool:
    lowered = text.lower()
    return any(trigger in lowered for trigger in COMBAT_TRIGGER_WORDS)


def roll_damage(attack: int) -> int:
    return random.randint(attack - 5, attack + 5)


def resolve_combat_round(action_text: str, stats: dict, enemy: dict) -> dict:
    """Resolve one round of combat with dice rolls - the LLM is not involved in the math."""
    action_lower = action_text.lower()
    summary_parts = []
    defending = False

    if "flee" in action_lower or "run" in action_lower or "escape" in action_lower:
        if random.random() < 0.4:
            summary_parts.append(f"You successfully flee from the {enemy['name']}.")
            return {"outcome": "fled", "summary": " ".join(summary_parts), "stats": stats, "enemy": enemy}
        summary_parts.append(f"You try to flee, but the {enemy['name']} blocks your escape.")

    elif "defend" in action_lower or "block" in action_lower or "guard" in action_lower:
        defending = True
        summary_parts.append(f"You raise your guard against the {enemy['name']}.")

    else:
        damage = max(0, roll_damage(stats["attack"]))
        enemy["hp"] = max(0, enemy["hp"] - damage)
        summary_parts.append(f"You attack the {enemy['name']} for {damage} damage.")
        if enemy["hp"] <= 0:
            summary_parts.append(f"The {enemy['name']} is defeated!")
            return {"outcome": "victory", "summary": " ".join(summary_parts), "stats": stats, "enemy": enemy}

    # Enemy retaliates - reached after a failed flee, a defend, or a non-lethal attack
    defence = stats["defence"] * (2 if defending else 1)
    damage = max(0, roll_damage(enemy["attack"]) - defence)
    stats["hp"] = max(0, stats["hp"] - damage)
    summary_parts.append(f"The {enemy['name']} strikes back for {damage} damage.")

    outcome = "defeat" if stats["hp"] <= 0 else "ongoing"
    if outcome == "defeat":
        summary_parts.append("You collapse, defeated.")

    return {"outcome": outcome, "summary": " ".join(summary_parts), "stats": stats, "enemy": enemy}


@app.get("/")
async def main_page():
    return "Hello World"


@app.post("/games", response_model=Game)
async def create_game(game: GameInput):
    new_game_id = "".join([random.choice(alphabet_list) for _ in range(10)])

    game_inputs = GameInput(
        player_name=game.player_name,
        setting=game.setting
    )

    game_output = await start_game(game_inputs)
    await save_game(new_game_id, game_inputs)

    new_game = Game(
        game_id=new_game_id,
        scene=game_output["scene"],
        actions=game_output["actions"],
        stats=Stats(**DEFAULT_STATS)
    )

    # Create character in "turns" table in database - no action has been taken yet
    await take_action_db(new_game_id, "", result=new_game.scene, stats=f"{DEFAULT_STATS}", turn_number=1)

    return new_game


@app.post("/games/{game_id}/action", response_model=Turn)
async def take_action(game_id: str, action: TurnInput):

    game_history = await get_game_history(game_id)
    previous_turn_number = game_history[0][2]

    # Record the player's chosen action against the turn it responds to
    await update_action(game_id=game_id, action=action.action, turn_number=previous_turn_number)

    stats_row = await get_last_turn(game_id)
    stats = ast.literal_eval(stats_row[-1])

    combat_row = await get_combat_state(game_id)
    combat_state = json.loads(combat_row[0]) if combat_row and combat_row[0] else {"in_combat": False}

    turn_number = previous_turn_number + 1

    if combat_state.get("in_combat"):
        enemy = combat_state["enemy"]
        round_result = resolve_combat_round(action.action, stats, enemy)
        stats = round_result["stats"]
        enemy = round_result["enemy"]
        outcome = round_result["outcome"]

        result_text = await narrate_combat(round_result["summary"])

        if outcome == "victory":
            combat_state = {"in_combat": False}
            actions = ["Search the fallen enemy for loot", "Catch your breath and take stock of your surroundings", "Press onward"]
        elif outcome == "fled":
            combat_state = {"in_combat": False}
            actions = ["Put some distance between yourself and the area", "Catch your breath", "Look for another way forward"]
        elif outcome == "defeat":
            combat_state = {"in_combat": False}
            actions = []
        else:
            combat_state = {"in_combat": True, "enemy": enemy}
            actions = ["Attack", "Defend", "Flee"]

        await update_combat_state(game_id, json.dumps(combat_state))

        game_over = stats["hp"] <= 0
        stats_str = str(stats)
        await take_action_db(game_id=game_id, action="", result=result_text, turn_number=turn_number, stats=stats_str)

        return Turn(
            result=result_text,
            actions=actions,
            turn=turn_number,
            stats=Stats(**stats),
            game_over=game_over,
            combat=CombatInfo(
                in_combat=combat_state["in_combat"],
                enemy_name=enemy["name"] if combat_state["in_combat"] else None,
                enemy_hp=enemy["hp"] if combat_state["in_combat"] else None
            )
        )

    # Not in combat - normal story flow. Re-fetch history so the LLM sees the action just recorded above
    game_history = await get_game_history(game_id)
    response = await continue_game(game_history, stats=stats)

    updates = response.get("updates")
    if isinstance(updates, dict):
        stats = apply_stat_updates(stats, updates)
    game_over = stats["hp"] <= 0
    stats_str = str(stats)

    combat_start = response.get("combat")
    triggered = isinstance(combat_start, dict) and isinstance(combat_start.get("enemy"), dict)
    if not triggered and detect_combat_trigger(response["result"]):
        triggered = True
        combat_start = {"enemy": DEFAULT_ENEMY.copy()}

    enemy = None
    if triggered and not game_over:
        enemy_data = combat_start["enemy"]
        enemy = {
            "name": enemy_data.get("name", DEFAULT_ENEMY["name"]),
            "hp": int(enemy_data.get("hp", DEFAULT_ENEMY["hp"])),
            "attack": int(enemy_data.get("attack", DEFAULT_ENEMY["attack"])),
        }
        combat_state = {"in_combat": True, "enemy": enemy}
        actions = ["Attack", "Defend", "Flee"]
    else:
        combat_state = {"in_combat": False}
        actions = [] if game_over else response["actions"]

    await update_combat_state(game_id, json.dumps(combat_state))

    # This turn's action is unknown until the player's next call updates it
    await take_action_db(game_id=game_id, action="", result=response["result"], turn_number=turn_number, stats=stats_str)

    turn = Turn(
        result=response["result"],
        actions=actions,
        turn=turn_number,
        stats=Stats(**stats),
        game_over=game_over,
        combat=CombatInfo(
            in_combat=combat_state["in_combat"],
            enemy_name=enemy["name"] if enemy else None,
            enemy_hp=enemy["hp"] if enemy else None
        )
    )
    return turn