import asyncio
from enum import Enum
from typing import List, Optional
from fastapi import FastAPI
from pydantic import BaseModel, Field
import string
import random
from db import init_db, save_game, take_action_db, get_game_history, get_last_turn, update_action
from contextlib import asynccontextmanager
from ai import start_game, continue_game

@asynccontextmanager
async def lifespan(app: FastAPI):
    await init_db()
    yield

app = FastAPI(lifespan=lifespan)

alphabet_list = list(string.ascii_letters)


class GameSetting(Enum):
    DARK_FANTASY = "dark fantasy"
    SPACE_OPERA = "space opera"
    POST_APOCALYPTIC = "post-apocalyptic"
    CLASSIC_DUNGEON = "classic dungeon"


class GameInput(BaseModel):
    player_name: str = Field(..., min_length=3, max_length=16, description="Player Name")
    setting: str = Field(default=GameSetting.CLASSIC_DUNGEON, description="Game setting")


class GameBase(BaseModel):
    scene: str = Field(..., description="Description of the scene generated by AI")
    actions: List[str] = Field(..., description="List of possible actions generated by AI")

class GameCreate(GameBase):
    pass


class Game(GameBase):
    game_id: str = Field(..., description="Unique identifier of the Game")


class Turn(BaseModel):
    result: str = Field(..., description="Result of the turn")
    actions: List[str] = Field(..., description="List of possible actions generated by AI")
    turn: int = Field(..., description="Turn number")


class TurnInput(BaseModel):
    action:str = Field(..., description="Your actions (choose one from the list e.g. 1, 2 or 3)")


@app.get("/")
async def main_page():
    return "Hello World"


@app.post("/games", response_model=Game)
async def create_game(game: GameInput):
    new_game_id = "".join([random.choice(alphabet_list) for _ in range(10)])

    game_inputs = GameInput(
        player_name=game.player_name,
        setting=game.setting
    )

    game_output = await start_game(game_inputs)
    await save_game(new_game_id, game_inputs)

    print(game_output)

    new_game = Game(
        game_id=new_game_id,
        scene=game_output["scene"],
        actions=game_output["actions"]
    )
    await take_action_db(new_game_id, new_game.actions[1], result=new_game.scene)

    return new_game


@app.post("/games/{game_id}/action", response_model=Turn)
async def take_action(game_id: str, action: TurnInput):

    action = TurnInput(action=action.action)
    game_history = await get_game_history(game_id)
    previous_turn_number = game_history[0][2]
    print(previous_turn_number)
    await update_action(game_id=game_id, action=action.action, turn_number=previous_turn_number)


    response = await continue_game(game_history)
    print(response)
    turn_number = previous_turn_number + 1
    print(turn_number)
    await take_action_db(game_id=game_id, action=action.action, result=response["result"], turn_number=turn_number)


    turn = Turn(
        result=response["result"],
        actions=response["actions"],
        turn=turn_number
    )
    return turn